/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./../components/header/dark-toggle.vue')['default']
    Header: typeof import('./../components/header/index.vue')['default']
    Logo: typeof import('./../components/header/logo.vue')['default']
    Nav: typeof import('./../components/header/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toggle: typeof import('./../components/header/toggle.vue')['default']
  }
}
